### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by yikuanglancheng**
a paper for physical layer "SigT: An Efficient End-to-End MIMO-OFDM Receiver Framework Based on Transformer"
github : https://github.com/SigTransformer/SigT

### CODE REVIEW

**Comment by liyiq5** [comment]
邮件已经收到，谢谢，祝好~！

**Comment by Charlie258** [comment]
你好，你的邮件已经收到，谢谢。

**Comment by LearnUgly** [comment]
感谢来信，您的邮件已经收到



At 2023-04-02 20:06:56, "xiuchengwang" ***@***.***> wrote:

a paper for physical layer "SigT: An Efficient End-to-End MIMO-OFDM Receiver Framework Based on Transformer"
github : https://github.com/SigTransformer/SigT

You can view, comment on, or merge this pull request online at:

  https://github.com/ML4Comm-Netw/Paper-with-Code-of-Wireless-communication-Based-on-DL/pull/34

Commit Summary
0c4d6e6 Merge pull request #2 from IIT-Lab/master
9b6ab82 Merge pull request #3 from IIT-Lab/master
89f0fe3 Update issue templates
1c1d28f Merge branch 'IIT-Lab:master' into master
8c1b1a5 add github action for daily arxiv
e161575 change days and files
dadbe72 change branch name
75e53f2 update today arxiv
f4936a6 Merge pull request #26 from zhuwenxing/master
21f833d Update daily.yml
84d96b5 Update README.md
File Changes

(6 files)

D.gitattributes (2)
A.github/workflows/daily.yml (47)
MREADME.md (5)
Adaily.json (1)
Adaily.md (23)
Adaily_arxiv.py (116)
Patch Links:
https://github.com/ML4Comm-Netw/Paper-with-Code-of-Wireless-communication-Based-on-DL/pull/34.patch
https://github.com/ML4Comm-Netw/Paper-with-Code-of-Wireless-communication-Based-on-DL/pull/34.diff

**Comment by Charlie258** [comment]
你好，你的邮件已经收到，谢谢。

**Comment by liyiq5** [comment]
邮件已经收到，谢谢，祝好~！

**Pull request closed without merging**
